# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8fab72695fff15d9c4461ab2964ff18f"
name = "3D Configurator"
application_url = "https://3d-configurator-production-f8a7.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/customer-deletion"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/data-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/gdpr/shop-deletion"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_draft_orders,read_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://3d-configurator-production-f8a7.up.railway.app/auth/callback",
  "https://3d-configurator-production-f8a7.up.railway.app/auth/shopify/callback",
  "https://3d-configurator-production-f8a7.up.railway.app/exitiframe"
]

[app_proxy]
url = "https://3d-configurator-production-f8a7.up.railway.app/api"
subpath = "polar3d"
prefix = "apps"

[pos]
embedded = false
 